name: Automation build images
run-name: Running build images

on:
  push:
    tags:
      - "v*"

jobs:
  build-app:
    name: Build React App into Distributable
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.upload-dist.outputs.artifact-id }}

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Save artifact
        id: upload-dist
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: dist/

  release-app:
    name: Release Build
    needs: build-app
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ needs.build-app.outputs.output1 }}

      - name: Compress artifact
        run: zip -r BRilianShop.zip ./*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: BRilianShop.zip

  build-image:
    name: Build Docker Image
    needs: release-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to GHCR
        run: |
          echo -n ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Build Docker image
        run: docker build --build-arg VITE_API_URL="${{ vars.VITE_API_URL }}" . -t ghcr.io/${{ github.repository }}:pra

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:pra

  deploy-image:
    name: Deploy to Server
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEYS }}
          script: |
            cd ~/brilianserver
            docker compose pull frontend
            docker compose up -d frontend